### ISSUE TITLE
where is the main ceml repo?

### ISSUE THREAD

**Issue by guaka** [jxe/groundcrew-viewer-jxe#32]
@jxe 

wanna make a note at https://github.com/Trustroots somewhere to implement it somehow (possibly through API)

notes:
- found some stuff at https://github.com/noahmiller/groundcrew-viewer/tree/master/ceml
- https://rubygems.org/gems/ceml/versions/0.9.0

**Comment by jxe** [comment]
Right here, this is a newer version than the ruby gem:  https://github.com/citizenlogistics/ceml
